### ISSUE TITLE
初学者的疑惑

### ISSUE THREAD

**Issue by yingmanwumen** [luojia65/w806-pac#2]
1. 这个项目已经结束了吗？我看到最后一次更新是在两天前，还需要志愿者做contribution吗
2. 作为初学者，我不是很明白我需要怎么做，有大哥可以提供相关的介绍和书籍、资料、链接等吗，例如我不是很明白svd文件是什么，打开看的时候发现是一个XML文件，里面有一些描述，根据README文档猜测这个文件会生成一些Rust代码。我应当去哪里寻找什么样的外设和相关的信息填入呢？

**Comment by apeng2012** [comment]
[https://www.keil.com/pack/doc/CMSIS/SVD/html/index.html](https://www.keil.com/pack/doc/CMSIS/SVD/html/index.html)

**Comment by luojia65** [comment]
暂时还没有结束，欢迎贡献！目前还只完成了2~3个外设的编写工作。
