### ISSUE TITLE
Datasheet 与 SDK 中寄存器内容不一致

### ISSUE THREAD

**Issue by apeng2012** [luojia65/w806-pac#5]
在PMU中断源寄存器的RTC中断标志位。
Datasheet 是 [5]
SDK 中 ```#define PMU_IF_RTC_Pos						(4)```

以 SDK 为准？

**Comment by luojia65** [comment]
先按sdk为准，在svd文件里编写一个注释，说明datasheet里和sdk有冲突。待未来rust代码验证时，再回来确认这里的内容
